[project]
name = "san-jose-animal-shelter-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "plotly>=6.4.0",
    "polars>=1.35.1",
]
